phisical_parameters:
  g: 9.80665
  m1: 1.0
  m2: 0.1
  l: 0.8
  external_force: 0


lqr:
  Q: [[1.0, 0.0, 0.0, 0.0],
      [0.0, 800.0, 0.0, 0.0],
      [0.0, 0.0, 10.0, 0.0],
      [0.0, 0.0, 0.0, 20.0]]
  R: [[0.44332]]
  # R: [[0.5]]

simulation:
  terminal_time: 20.0
  discrete_time: 0.05
  x0: [0.0, -0.1, 0.0, 0.0]


